name: 'GDrive download'
description: 'Downloads from Google Drive'
inputs:
  local_folder:
    description: 'Local destination'
    required: true
  gdrive_folder_id:
    description: 'Google Drive folder ID'
    required: true
  gdrive_subfolder:
    description: 'GDrive subfolder'
    required: false
    default: '.'
  gdrive_credentials:
    description: 'Google Drive base64 credentials'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download
      shell: bash
      run: |
          mkdir -p ${{inputs.local_folder}}
          python ./src/gdrive.py download -l ${{inputs.local_folder}} -d ${{inputs.gdrive_folder_id}} -s ${{inputs.gdrive_subfolder}} -c ${{inputs.gdrive_credentials}}