name: GitHub scheduled action
on:
  push:
  #schedule:
  #  - cron: '*/15 6-22 * * *'
jobs:
  Collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install python dependencies
        run: |
          pip install -r extern/fusnic/requirements.txt
          pip install -r requirements.txt
      - name: Collect data
        run: python collect_fusionsolar.py -o output -u ${{secrets.FUSIONSOLAR_USER}} -p ${{secrets.FUSIONSOLAR_PASSWORD}}
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: collected-data
          path: output/
      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: output/*
          folderId: ${{ secrets.GDRIVE_FOLDER }}
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          encoded: true
