name: GitHub scheduled action
on:
  push:
  #schedule:
  #  - cron: '*/15 6-22 * * *'
jobs:
  FusionSolar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./extern/fusnic/.github/actions/setup_python
      - name: Collect data
        run: |
          mkdir -p data/raw/fusion_solar
          python etl_collect_fus.py -o data/raw/fusion_solar -u ${{secrets.FUSIONSOLAR_USER}} -p ${{secrets.FUSIONSOLAR_PASSWORD}} --mock
      - name: Standardize data
        run: |
          mkdir -p data/std/fusion_solar
          python etl_standardize.py -s data/raw/fusion_solar -d data/std/fusion_solar -c src/fus2std.json
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fusion_solar
          path: data
      - name: Upload to Google Drive
        uses: ./.github/actions/gdrive_upload
        with:
          local_folder: 'data'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
  Aggregate:
    needs: FusionSolar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./extern/fusnic/.github/actions/setup_python
      - name: Download from Google Drive
        uses: ./.github/actions/gdrive_download
        with:
          local_folder: 'data/std'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_subfolder: 'std'
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
      - name: Aggregate data
        run: |
          mkdir -p data/agg
          python etl_aggregate.py -s data/std -d data/agg
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aggregated
          path: data/agg
      - name: Upload to Google Drive
        uses: ./.github/actions/gdrive_upload
        with:
          local_folder: 'data/agg'
          gdrive_subfolder: 'agg'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
