name: GitHub scheduled action
on:
  push:
  #schedule:
  #  - cron: '*/15 6-22 * * *'
jobs:
  FusionSolar_Collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./extern/fusnic/.github/actions/setup_python
      - name: Collect data
        run: |
          mkdir output
          python etl_collect_fus.py -o output -u ${{secrets.FUSIONSOLAR_USER}} -p ${{secrets.FUSIONSOLAR_PASSWORD}}
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fus_collected-data
          path: output
  FusionSolar_Update:
    needs: FusionSolar_Collect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./extern/fusnic/.github/actions/setup_python
      - name: Download from Google Drive
        run: |
          mkdir previous
          python gdrive.py download -l previous -d ${{secrets.GDRIVE_FOLDER}} -c ${{secrets.GDRIVE_CREDENTIALS}}
      - name: Download latest artifacts
        uses: actions/download-artifact@v3
        with:
          name: fus_collected-data
          path: latest/fusion_solar
      - name: Update data
        run: |
          mkdir -p updated/fusion_solar
          python etl_update.py -p previous/fusion_solar -l latest/fusion_solar -u updated/fusion_solar
          mkdir -p updated/std
          python etl_update.py -p previous/std -l latest/fusion_solar -u updated/std -r src/fus2std.json
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: updated-data
          path: updated
      - name: Upload to Google Drive
        run: |
          python gdrive.py upload -l updated -d ${{secrets.GDRIVE_FOLDER}} -c ${{secrets.GDRIVE_CREDENTIALS}}
