name: GitHub scheduled action
on:
  push:
    branches:
      - '*'
      - 'main'
  schedule:
    - cron: '20 21 * * *'
jobs:
  Configure:
    runs-on: ubuntu-latest
    steps:
      - name: Branch check
        id: branch_check
        run: |
          echo "Running on branch ${{github.ref}}"
          if [ "${{github.ref}}" = "refs/heads/main" ]; then
            echo "::set-output name=environment::Production"
          else
            echo "::set-output name=environment::Test"
          fi
      - name: Output environment
        run: echo "Environment ${{steps.branch_check.outputs.environment}}"
    outputs:
      environment: ${{steps.branch_check.outputs.environment}}
      
  FusionSolar:
    runs-on: ubuntu-latest
    needs: [Configure]
    environment: 
      name: ${{needs.Configure.outputs.environment}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./.github/actions/setup_python
      - name: Collect data
        run: |
          mkdir -p data/raw/fusion_solar
          python etl_collect_fus.py -o data/raw/fusion_solar -u ${{secrets.FUSIONSOLAR_USER}} -p ${{secrets.FUSIONSOLAR_PASSWORD}}
      - name: Standardize data
        run: |
          mkdir -p data/std/fusion_solar
          python etl_standardize.py -s data/raw/fusion_solar -d data/std/fusion_solar -c src/fus2std.json
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fusion_solar
          path: data
      - name: Upload to Google Drive
        uses: ./.github/actions/gdrive_upload
        with:
          local_folder: 'data'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
  Aggregate:
    needs: [FusionSolar, Configure]
    environment: 
      name: ${{needs.Configure.outputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./.github/actions/setup_python
      - name: Download from Google Drive
        uses: ./.github/actions/gdrive_download
        with:
          local_folder: 'data/std'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_subfolder: 'std'
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
      - name: Aggregate data
        run: |
          mkdir -p data/agg
          python etl_aggregate.py -s data/std -d data/agg
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aggregated
          path: data/agg
      - name: Upload to Google Drive
        uses: ./.github/actions/gdrive_upload
        with:
          local_folder: 'data/agg'
          gdrive_subfolder: 'agg'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
