name: GitHub scheduled action
on:
  push:
  #schedule:
  #  - cron: '*/15 6-22 * * *'
jobs:
  FusionSolar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./extern/fusnic/.github/actions/setup_python
      - name: Collect data
        run: |
          mkdir -p data/raw/fusion_solar
          python etl_collect_fus.py -o data/raw/fusion_solar -u ${{secrets.FUSIONSOLAR_USER}} -p ${{secrets.FUSIONSOLAR_PASSWORD}}
      - name: Standardize data
        run: |
          mkdir -p data/std/fusion_solar
          python etl_update.py -l data/raw/fusion_solar -u data/std/fusion_solar -r src/fus2std.json
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fusion_solar
          path: data
      - name: Upload to Google Drive
        uses: ./.github/actions/gdrive_upload
        with:
          local_folder: 'data'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
  Merge:
    needs: FusionSolar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./extern/fusnic/.github/actions/setup_python
      - name: Download from Google Drive
        uses: ./.github/actions/gdrive_download
        with:
          local_folder: 'data'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
      - name: Merge data
        run: |
          mkdir -p data/updated/merged
          python etl_update.py -p data/std/merged -l data/std/fusion_solar -u data/updated/merged
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: merged
          path: data/updated/merged
      - name: Upload to Google Drive
        uses: ./.github/actions/gdrive_upload
        with:
          local_folder: 'data/updated/merged'
          gdrive_subfolder: 'std/merged'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
