name: GitHub scheduled action
on:
  push:
  #schedule:
  #  - cron: '*/15 6-22 * * *'
jobs:
  FusionSolar_Collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./extern/fusnic/.github/actions/setup_python
      - name: Collect data
        run: |
          mkdir -p data/output
          python etl_collect_fus.py -o data/output -u ${{secrets.FUSIONSOLAR_USER}} -p ${{secrets.FUSIONSOLAR_PASSWORD}}
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fus_collected-data
          path: data/output
  FusionSolar_Update:
    needs: FusionSolar_Collect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup python
        uses: ./extern/fusnic/.github/actions/setup_python
      - name: Download from Google Drive
        uses: ./.github/actions/gdrive_download
        with:
          local_folder: 'data/previous'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
      - name: Download latest artifacts
        uses: actions/download-artifact@v3
        with:
          name: fus_collected-data
          path: data/latest/fusion_solar
      - name: Update data
        run: |
          mkdir -p data/updated/fusion_solar
          python etl_update.py -p data/previous/fusion_solar -l data/latest/fusion_solar -u data/updated/fusion_solar
          mkdir -p data/updated/std
          python etl_update.py -p data/previous/std -l data/latest/fusion_solar -u data/updated/std -r src/fus2std.json
      - name: Uploads artifacts
        uses: actions/upload-artifact@v3
        with:
          name: updated-data
          path: data/updated
      - name: Upload to Google Drive
        uses: ./.github/actions/gdrive_upload
        with:
          local_folder: 'data/updated'
          gdrive_folder_id: ${{secrets.GDRIVE_FOLDER}}
          gdrive_credentials: ${{secrets.GDRIVE_CREDENTIALS}}
